<?xml version="1.0" encoding="UTF-8"?>
<problems>
    <problem>
        <file>model_b.py</file>
        <line>5</line>
        <module>light_idea_test_case</module>
        <entry_point TYPE="file" FQNAME="temp:///src/odoo/addons/model_names/models/model_b.py" />
        <problem_class severity="ERROR" attribute_key="WRONG_REFERENCES_ATTRIBUTES">Reference to a missing model definition</problem_class>
        <description>Missing model definition for not_model_b</description>
    </problem>
    <problem>
        <file>test_models.py</file>
        <line>10</line>
        <module>light_idea_test_case</module>
        <entry_point TYPE="file" FQNAME="temp:///src/test_models.py" />
        <problem_class severity="ERROR" attribute_key="WRONG_REFERENCES_ATTRIBUTES">Reference to a missing model definition</problem_class>
        <description>Missing model definition for idontknow</description>
    </problem>
    <problem>
        <file>test_models.py</file>
        <line>18</line>
        <module>light_idea_test_case</module>
        <entry_point TYPE="file" FQNAME="temp:///src/test_models.py" />
        <problem_class severity="ERROR" attribute_key="WRONG_REFERENCES_ATTRIBUTES">Reference to a missing model definition</problem_class>
        <description>Missing model definition for not_existing_model</description>
    </problem>
    <problem>
        <file>test_models.py</file>
        <line>18</line>
        <module>light_idea_test_case</module>
        <entry_point TYPE="file" FQNAME="temp:///src/test_models.py" />
        <problem_class severity="ERROR" attribute_key="WRONG_REFERENCES_ATTRIBUTES">Reference to a missing model definition</problem_class>
        <description>Missing model definition for not_existing_model</description>
    </problem>
</problems>